export const RECIPE_TREE_ITEM_ADDED = 'RECIPE_TREE_ITEM_ADDED';
export const RECIPE_TREE_ITEM_MOVED = 'RECIPE_TREE_ITEM_MOVED';
export const RECIPE_TREE_LINK_CREATED = 'RECIPE_TREE_LINK_CREATED';
export const RECIPE_TREE_LAYOUT_CHANGED = 'RECIPE_TREE_LAYOUT_CHANGED';
export const RECIPE_TREE_CLIENT_RECT_UPDATED = 'RECIPE_TREE_CLIENT_RECT_UPDATED';
export const RECIPE_TREE_COUNTS_UPDATED = 'RECIPE_TREE_COUNTS_UPDATED';

export const FACTORIO_DATA_FETCH_STARTED = 'FACTORIO_DATA_FETCH_STARTED';
export const FACTORIO_DATA_LOADED = 'FACTORIO_DATA_LOADED';
export const FACTORIO_DATA_FETCHING_FAILED = 'FACTORIO_DATA_FETCHING_FAILED';

export const RECIPE_PICKER_HIDE = 'RECIPE_PICKER_HIDE';
export const RECIPE_PICKER_SHOW = 'RECIPE_PICKER_SHOW';

export const FLOATING_ELEMENT_SHOW = 'FLOATING_ELEMENT_SHOW';
export const FLOATING_ELEMENT_MOVE_RELATIVE = 'FLOATING_ELEMENT_MOVE_RELATIVE';
export const FLOATING_ELEMENT_HIDE = 'FLOATING_ELEMENT_HIDE';
